---
# "Lowest" section in the Heat Orchestration Template
description: Template to create a single C2 Satellite Server Instance
heat_template_version: 2017-02-24
parameters:
  flavor:
    type: string
  image:
    type: string
  key_name:
    type: string
  name:
    type: string
  c2_network:
    type: string
  c2_subnet:
    type: string
  public_network:
    type: string
  security_group:
    type: string
  server_group:
    type: string

resources:

  server:
    type: OS::Nova::Server
    properties:
      name: { get_param: name }
      image: { get_param: image }
      flavor: { get_param: flavor }
      key_name: { get_param: key_name }
      networks:
        - port: { get_resource: c2_port }
      scheduler_hints: { group: { get_param: server_group } }

  c2_port:
    type: OS::Neutron::Port
    properties:
      network: { get_param: c2_network }
      security_groups:
        - { get_param: security_group }
      fixed_ips:
        - subnet: { get_param: c2_subnet }
      replacement_policy: AUTO

  c2_floating:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: { get_param: public_network }
      port_id: { get_resource: c2_port }

outputs:
  satellite_server_attributes:
    value:
      name: { get_attr: [server, name] }
      private_ip: { get_attr: [server, first_address ] }
      floating_ip: { get_attr: [c2_floating, floating_ip_address] }

